#!/usr/bin/env python
"""Generate publication pages from timeline grant IDs using PubMed.

This script reads CPRIT-style grant IDs from `_data/timeline.yml`, queries
PubMed's grants/funding field, and writes publication markdown files into
`_publications/`.

The output is designed to be safe to rerun:
- files previously generated by this script can be refreshed
- duplicate PubMed hits across multiple grants are merged into one page
- cleanup only removes files previously generated by this script
"""

from __future__ import annotations

import argparse
import html
import re
import sys
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
TIMELINE_PATH = ROOT / "_data" / "timeline.yml"
PUBLICATIONS_DIR = ROOT / "_publications"
OUTPUT_DIR = PUBLICATIONS_DIR
GENERATED_BY = "markdown_generator/publications_from_timeline_grants.py"
TOOL_NAME = "tamu-3drc-publication-generator"
EMAIL = "nnguyen@tamu.edu"
GRANT_PATTERN = re.compile(r"\b(RP\d{6})(-[A-Z0-9]+)?\b")
MONTHS = {
    "jan": "01",
    "feb": "02",
    "mar": "03",
    "apr": "04",
    "may": "05",
    "jun": "06",
    "jul": "07",
    "aug": "08",
    "sep": "09",
    "oct": "10",
    "nov": "11",
    "dec": "12",
}


@dataclass
class Publication:
    pmid: str
    title: str
    venue: str
    date: str
    authors: list[str]
    abstract: str = ""
    doi: str | None = None
    grants: set[str] = field(default_factory=set)
    matched_terms: set[str] = field(default_factory=set)


def collapse_ws(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()


def html_escape(text: str) -> str:
    return "".join(
        {
            "&": "&amp;",
            '"': "&quot;",
            "'": "&apos;",
        }.get(char, char)
        for char in text
    )


def normalize_title(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def slugify(value: str) -> str:
    ascii_value = (
        unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    )
    slug = re.sub(r"[^A-Za-z0-9]+", "-", ascii_value).strip("-")
    slug = re.sub(r"-{2,}", "-", slug)
    return slug or "publication"


def extract_timeline_grants(path: Path) -> dict[str, set[str]]:
    text = path.read_text(encoding="utf-8")
    grants: dict[str, set[str]] = defaultdict(set)
    for match in GRANT_PATTERN.finditer(text):
        base = match.group(1)
        full = match.group(0)
        grants[base].add(base)
        grants[base].add(full)
    return dict(sorted(grants.items()))


def parse_existing_publications() -> tuple[set[str], set[str], dict[Path, str]]:
    pmids: set[str] = set()
    titles: set[str] = set()
    generated_files: dict[Path, str] = {}

    for path in PUBLICATIONS_DIR.rglob("*.md"):
        text = path.read_text(encoding="utf-8")
        match = re.match(r"---\n(.*?)\n---", text, re.DOTALL)
        if not match:
            continue

        frontmatter = match.group(1)
        title_match = re.search(r'^title:\s*"(.*)"\s*$', frontmatter, re.MULTILINE)
        pmid_match = re.search(r"^pmid:\s*'?(.*?)'?\s*$", frontmatter, re.MULTILINE)
        generated_match = re.search(
            r"^generated_by:\s*'?(.*?)'?\s*$", frontmatter, re.MULTILINE
        )

        if title_match:
            titles.add(normalize_title(title_match.group(1)))
        if pmid_match:
            pmids.add(pmid_match.group(1).strip())
        if generated_match:
            generated_files[path] = generated_match.group(1).strip()

    return pmids, titles, generated_files


class NCBIClient:
    def __init__(self, delay_seconds: float = 0.4) -> None:
        self.delay_seconds = delay_seconds
        self.last_request_at = 0.0

    def _wait(self) -> None:
        elapsed = time.time() - self.last_request_at
        if elapsed < self.delay_seconds:
            time.sleep(self.delay_seconds - elapsed)

    def _get_xml(self, endpoint: str, params: dict[str, str]) -> ET.Element:
        merged = {
            "tool": TOOL_NAME,
            "email": EMAIL,
            **params,
        }
        url = (
            "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
            f"{endpoint}?{urllib.parse.urlencode(merged)}"
        )

        attempts = 0
        while True:
            self._wait()
            request = urllib.request.Request(
                url,
                headers={"User-Agent": f"{TOOL_NAME} ({EMAIL})"},
            )
            try:
                with urllib.request.urlopen(request, timeout=30) as response:
                    self.last_request_at = time.time()
                    return ET.fromstring(response.read())
            except urllib.error.HTTPError as exc:
                attempts += 1
                if exc.code == 429 and attempts < 4:
                    time.sleep(2 * attempts)
                    continue
                raise

    def esearch(self, term: str) -> list[str]:
        root = self._get_xml(
            "esearch.fcgi",
            {
                "db": "pubmed",
                "term": term,
                "retmax": "200",
                "retmode": "xml",
                "sort": "pub date",
            },
        )
        return [node.text for node in root.findall("./IdList/Id") if node.text]

    def efetch(self, pmids: list[str]) -> list[Publication]:
        if not pmids:
            return []

        root = self._get_xml(
            "efetch.fcgi",
            {
                "db": "pubmed",
                "id": ",".join(pmids),
                "retmode": "xml",
            },
        )

        publications: list[Publication] = []
        for article in root.findall("./PubmedArticle"):
            publication = parse_pubmed_article(article)
            if publication:
                publications.append(publication)
        return publications


def text_or_none(node: ET.Element | None) -> str | None:
    if node is None:
        return None
    return collapse_ws("".join(node.itertext()))


def parse_pubmed_date(article: ET.Element) -> str:
    article_date = article.find(".//Article/ArticleDate")
    if article_date is not None:
        year = text_or_none(article_date.find("Year")) or "1900"
        month = text_or_none(article_date.find("Month")) or "01"
        day = text_or_none(article_date.find("Day")) or "01"
        return f"{year}-{month.zfill(2)}-{day.zfill(2)}"

    pub_date = article.find(".//JournalIssue/PubDate")
    year = text_or_none(pub_date.find("Year") if pub_date is not None else None) or "1900"
    month_raw = text_or_none(pub_date.find("Month") if pub_date is not None else None) or "01"
    day_raw = text_or_none(pub_date.find("Day") if pub_date is not None else None) or "01"

    month_key = month_raw[:3].lower()
    month = MONTHS.get(month_key, month_raw.zfill(2) if month_raw.isdigit() else "01")
    day = day_raw.zfill(2) if day_raw.isdigit() else "01"
    return f"{year}-{month}-{day}"


def parse_authors(article: ET.Element) -> list[str]:
    authors: list[str] = []
    for author in article.findall(".//AuthorList/Author"):
        collective = text_or_none(author.find("CollectiveName"))
        if collective:
            authors.append(collective)
            continue

        last = text_or_none(author.find("LastName"))
        initials = text_or_none(author.find("Initials"))
        if last and initials:
            authors.append(f"{last} {initials}")
        elif last:
            authors.append(last)
    return authors


def parse_pubmed_article(article: ET.Element) -> Publication | None:
    pmid = text_or_none(article.find("./MedlineCitation/PMID"))
    title = text_or_none(article.find(".//ArticleTitle"))
    venue = text_or_none(article.find(".//Journal/Title")) or "PubMed"

    if not pmid or not title:
        return None

    abstract_parts = [
        collapse_ws("".join(node.itertext()))
        for node in article.findall(".//Abstract/AbstractText")
    ]
    abstract = "\n\n".join(part for part in abstract_parts if part)

    doi = None
    for article_id in article.findall(".//PubmedData/ArticleIdList/ArticleId"):
        if article_id.attrib.get("IdType") == "doi" and article_id.text:
            doi = article_id.text.strip()
            break

    grants = set()
    for grant in article.findall(".//GrantList/Grant"):
        grant_id = text_or_none(grant.find("GrantID"))
        if grant_id:
            grants.add(grant_id)

    return Publication(
        pmid=pmid,
        title=title,
        venue=venue,
        date=parse_pubmed_date(article),
        authors=parse_authors(article),
        abstract=abstract,
        doi=doi,
        grants=grants,
    )


def build_citation(publication: Publication) -> str:
    author_text = ", ".join(publication.authors[:8])
    if len(publication.authors) > 8:
        author_text += ", et al."
    if not author_text:
        author_text = "Unknown authors"

    year = publication.date[:4]
    return f'{author_text}. "{publication.title}." {publication.venue}, {year}.'


def build_search_term(base_grant: str, aliases: set[str]) -> str:
    parts = [f'"{grant}"[gr]' for grant in sorted(aliases)]
    parts.append(f'"{base_grant}"[All Fields]')
    return " OR ".join(parts)


def build_markdown(publication: Publication) -> str:
    slug = slugify(publication.title)
    html_filename = f"{publication.date}-{slug}"
    citation = html_escape(build_citation(publication))
    title = html_escape(publication.title)
    venue = html_escape(publication.venue)
    abstract = html_escape(publication.abstract)
    matched_grants = ", ".join(f"`{grant}`" for grant in sorted(publication.matched_terms))
    funding_grants = ", ".join(sorted(publication.grants)) or "Not listed in PubMed metadata"
    paper_url = f"https://doi.org/{publication.doi}" if publication.doi else f"https://pubmed.ncbi.nlm.nih.gov/{publication.pmid}/"

    pubmed_grants_lines = [f"  - {grant}" for grant in sorted(publication.grants)]
    if not pubmed_grants_lines:
        pubmed_grants_lines = ["  - unknown"]

    lines = [
        "---",
        f'title: "{title}"',
        "collection: publications",
        "category: manuscripts",
        f"permalink: /publication/{html_filename}",
        f"date: {publication.date}",
        f"venue: '{venue}'",
        f"paperurl: '{paper_url}'",
        f"pmid: '{publication.pmid}'",
    ]

    if publication.doi:
        lines.append(f"doi: '{publication.doi}'")

        lines.extend(
        [
            "grants:",
            *[f"  - {grant}" for grant in sorted(publication.matched_terms)],
            "pubmed_grants:",
            *pubmed_grants_lines,
            "generated: true",
            f"generated_by: '{GENERATED_BY}'",
            f"citation: '{citation}'",
            "---",
            "",
            f"Matched timeline grants: {matched_grants}",
            "",
            f"PubMed funding metadata: `{funding_grants}`",
            "",
            f"[PubMed record](https://pubmed.ncbi.nlm.nih.gov/{publication.pmid}/){{:target=\"_blank\"}}",
            "",
            f"[Access paper here]({paper_url}){{:target=\"_blank\"}}",
        ]
    )

    if abstract:
        lines.extend(["", abstract])

    return "\n".join(lines) + "\n"


def write_publication(
    publication: Publication,
    existing_pmids: set[str],
    existing_titles: set[str],
    dry_run: bool,
) -> tuple[str, Path]:
    slug = slugify(publication.title)
    filename = f"{publication.date}-{slug}.md"
    path = OUTPUT_DIR / filename

    title_key = normalize_title(publication.title)
    if publication.pmid in existing_pmids and not path.exists():
        return "skipped-existing", path
    if title_key in existing_titles and not path.exists():
        return "skipped-existing", path

    content = build_markdown(publication)
    if not dry_run:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    existing_pmids.add(publication.pmid)
    existing_titles.add(title_key)
    return "written", path


def clean_stale_generated_files(
    generated_paths: set[Path],
    known_generated_files: dict[Path, str],
    dry_run: bool,
) -> list[Path]:
    stale: list[Path] = []
    for path, generator in known_generated_files.items():
        if generator != GENERATED_BY:
            continue
        if path not in generated_paths:
            stale.append(path)
            if not dry_run and path.exists():
                path.unlink()
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate publication markdown from timeline grants via PubMed."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview matched publications without writing files.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove stale files previously generated by this script.",
    )
    args = parser.parse_args()

    grant_groups = extract_timeline_grants(TIMELINE_PATH)
    existing_pmids, existing_titles, known_generated_files = parse_existing_publications()
    client = NCBIClient()

    publications_by_pmid: dict[str, Publication] = {}
    grant_hit_counts: dict[str, int] = {}

    for base_grant, aliases in grant_groups.items():
        term = build_search_term(base_grant, aliases)
        try:
            pmids = client.esearch(term)
        except Exception as exc:  # pragma: no cover - network path
            print(f"[error] search failed for {base_grant}: {exc}", file=sys.stderr)
            continue

        grant_hit_counts[base_grant] = len(pmids)
        for batch_start in range(0, len(pmids), 100):
            batch = pmids[batch_start : batch_start + 100]
            try:
                batch_publications = client.efetch(batch)
            except Exception as exc:  # pragma: no cover - network path
                print(f"[error] fetch failed for {base_grant}: {exc}", file=sys.stderr)
                continue

            for publication in batch_publications:
                current = publications_by_pmid.get(publication.pmid)
                if current is None:
                    current = publication
                    publications_by_pmid[publication.pmid] = current
                current.matched_terms.add(base_grant)
                current.grants.update(publication.grants)

    generated_paths: set[Path] = set()
    written = 0
    skipped = 0

    for publication in sorted(
        publications_by_pmid.values(),
        key=lambda item: (item.date, item.title.lower()),
    ):
        status, path = write_publication(
            publication,
            existing_pmids,
            existing_titles,
            dry_run=args.dry_run,
        )
        if status == "written":
            written += 1
            generated_paths.add(path)
        else:
            skipped += 1

    stale = clean_stale_generated_files(
        generated_paths,
        known_generated_files,
        dry_run=args.dry_run,
    ) if args.clean else []

    print("Timeline grant search summary:")
    for grant_id, count in grant_hit_counts.items():
        print(f"  {grant_id}: {count} PubMed matches")

    print("")
    print(f"Unique PubMed publications found: {len(publications_by_pmid)}")
    print(f"Files {'to write' if args.dry_run else 'written'}: {written}")
    print(f"Files skipped due to existing publications: {skipped}")
    if args.clean:
        print(f"Stale generated files {'to remove' if args.dry_run else 'removed'}: {len(stale)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
